// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: \\vmware-host/Shared Folders/�ĸ�/afterworkdev/smile/src/Smile/src/com/heme/logic/module/protos/access.proto

package com.heme.logic.module;

public final class Access {
  private Access() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface AccessReqOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required uint64 uint64_uid = 1;
    /**
     * <code>required uint64 uint64_uid = 1;</code>
     *
     * <pre>
     *帐号
     * </pre>
     */
    boolean hasUint64Uid();
    /**
     * <code>required uint64 uint64_uid = 1;</code>
     *
     * <pre>
     *帐号
     * </pre>
     */
    long getUint64Uid();

    // required uint32 uint32_seq = 2;
    /**
     * <code>required uint32 uint32_seq = 2;</code>
     *
     * <pre>
     *请求包序号
     * </pre>
     */
    boolean hasUint32Seq();
    /**
     * <code>required uint32 uint32_seq = 2;</code>
     *
     * <pre>
     *请求包序号
     * </pre>
     */
    int getUint32Seq();

    // required string str_cmd = 3;
    /**
     * <code>required string str_cmd = 3;</code>
     *
     * <pre>
     *请求的命令字
     * </pre>
     */
    boolean hasStrCmd();
    /**
     * <code>required string str_cmd = 3;</code>
     *
     * <pre>
     *请求的命令字
     * </pre>
     */
    java.lang.String getStrCmd();
    /**
     * <code>required string str_cmd = 3;</code>
     *
     * <pre>
     *请求的命令字
     * </pre>
     */
    com.google.protobuf.ByteString
        getStrCmdBytes();

    // required bytes bytes_body = 4;
    /**
     * <code>required bytes bytes_body = 4;</code>
     *
     * <pre>
     *请求信令包体，该字段为protocol序列化内容
     * </pre>
     */
    boolean hasBytesBody();
    /**
     * <code>required bytes bytes_body = 4;</code>
     *
     * <pre>
     *请求信令包体，该字段为protocol序列化内容
     * </pre>
     */
    com.google.protobuf.ByteString getBytesBody();
  }
  /**
   * Protobuf type {@code AccessReq}
   *
   * <pre>
   *客户端所有信令，发出前均通过该协议包装
   *请求中 uint32_seq 用来标记请求的序号，接入svr回包时会填上
   *请求中 str_cmd 用来表示请求的类型，svr收到后会依照请求命令字来解 bytes_body
   * </pre>
   */
  public static final class AccessReq extends
      com.google.protobuf.GeneratedMessage
      implements AccessReqOrBuilder {
    // Use AccessReq.newBuilder() to construct.
    private AccessReq(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private AccessReq(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final AccessReq defaultInstance;
    public static AccessReq getDefaultInstance() {
      return defaultInstance;
    }

    public AccessReq getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private AccessReq(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              uint64Uid_ = input.readUInt64();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              uint32Seq_ = input.readUInt32();
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              strCmd_ = input.readBytes();
              break;
            }
            case 34: {
              bitField0_ |= 0x00000008;
              bytesBody_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Access.internal_static_AccessReq_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Access.internal_static_AccessReq_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Access.AccessReq.class, Access.AccessReq.Builder.class);
    }

    public static com.google.protobuf.Parser<AccessReq> PARSER =
        new com.google.protobuf.AbstractParser<AccessReq>() {
      public AccessReq parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new AccessReq(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<AccessReq> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required uint64 uint64_uid = 1;
    public static final int UINT64_UID_FIELD_NUMBER = 1;
    private long uint64Uid_;
    /**
     * <code>required uint64 uint64_uid = 1;</code>
     *
     * <pre>
     *帐号
     * </pre>
     */
    public boolean hasUint64Uid() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required uint64 uint64_uid = 1;</code>
     *
     * <pre>
     *帐号
     * </pre>
     */
    public long getUint64Uid() {
      return uint64Uid_;
    }

    // required uint32 uint32_seq = 2;
    public static final int UINT32_SEQ_FIELD_NUMBER = 2;
    private int uint32Seq_;
    /**
     * <code>required uint32 uint32_seq = 2;</code>
     *
     * <pre>
     *请求包序号
     * </pre>
     */
    public boolean hasUint32Seq() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required uint32 uint32_seq = 2;</code>
     *
     * <pre>
     *请求包序号
     * </pre>
     */
    public int getUint32Seq() {
      return uint32Seq_;
    }

    // required string str_cmd = 3;
    public static final int STR_CMD_FIELD_NUMBER = 3;
    private java.lang.Object strCmd_;
    /**
     * <code>required string str_cmd = 3;</code>
     *
     * <pre>
     *请求的命令字
     * </pre>
     */
    public boolean hasStrCmd() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required string str_cmd = 3;</code>
     *
     * <pre>
     *请求的命令字
     * </pre>
     */
    public java.lang.String getStrCmd() {
      java.lang.Object ref = strCmd_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          strCmd_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string str_cmd = 3;</code>
     *
     * <pre>
     *请求的命令字
     * </pre>
     */
    public com.google.protobuf.ByteString
        getStrCmdBytes() {
      java.lang.Object ref = strCmd_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        strCmd_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // required bytes bytes_body = 4;
    public static final int BYTES_BODY_FIELD_NUMBER = 4;
    private com.google.protobuf.ByteString bytesBody_;
    /**
     * <code>required bytes bytes_body = 4;</code>
     *
     * <pre>
     *请求信令包体，该字段为protocol序列化内容
     * </pre>
     */
    public boolean hasBytesBody() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>required bytes bytes_body = 4;</code>
     *
     * <pre>
     *请求信令包体，该字段为protocol序列化内容
     * </pre>
     */
    public com.google.protobuf.ByteString getBytesBody() {
      return bytesBody_;
    }

    private void initFields() {
      uint64Uid_ = 0L;
      uint32Seq_ = 0;
      strCmd_ = "";
      bytesBody_ = com.google.protobuf.ByteString.EMPTY;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasUint64Uid()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasUint32Seq()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasStrCmd()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasBytesBody()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeUInt64(1, uint64Uid_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeUInt32(2, uint32Seq_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getStrCmdBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBytes(4, bytesBody_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(1, uint64Uid_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(2, uint32Seq_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getStrCmdBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, bytesBody_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static Access.AccessReq parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Access.AccessReq parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Access.AccessReq parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Access.AccessReq parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Access.AccessReq parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static Access.AccessReq parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static Access.AccessReq parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static Access.AccessReq parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static Access.AccessReq parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static Access.AccessReq parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(Access.AccessReq prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code AccessReq}
     *
     * <pre>
     *客户端所有信令，发出前均通过该协议包装
     *请求中 uint32_seq 用来标记请求的序号，接入svr回包时会填上
     *请求中 str_cmd 用来表示请求的类型，svr收到后会依照请求命令字来解 bytes_body
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements Access.AccessReqOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return Access.internal_static_AccessReq_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return Access.internal_static_AccessReq_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                Access.AccessReq.class, Access.AccessReq.Builder.class);
      }

      // Construct using Access.AccessReq.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        uint64Uid_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000001);
        uint32Seq_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        strCmd_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        bytesBody_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return Access.internal_static_AccessReq_descriptor;
      }

      public Access.AccessReq getDefaultInstanceForType() {
        return Access.AccessReq.getDefaultInstance();
      }

      public Access.AccessReq build() {
        Access.AccessReq result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public Access.AccessReq buildPartial() {
        Access.AccessReq result = new Access.AccessReq(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.uint64Uid_ = uint64Uid_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.uint32Seq_ = uint32Seq_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.strCmd_ = strCmd_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.bytesBody_ = bytesBody_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof Access.AccessReq) {
          return mergeFrom((Access.AccessReq)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(Access.AccessReq other) {
        if (other == Access.AccessReq.getDefaultInstance()) return this;
        if (other.hasUint64Uid()) {
          setUint64Uid(other.getUint64Uid());
        }
        if (other.hasUint32Seq()) {
          setUint32Seq(other.getUint32Seq());
        }
        if (other.hasStrCmd()) {
          bitField0_ |= 0x00000004;
          strCmd_ = other.strCmd_;
          onChanged();
        }
        if (other.hasBytesBody()) {
          setBytesBody(other.getBytesBody());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasUint64Uid()) {
          
          return false;
        }
        if (!hasUint32Seq()) {
          
          return false;
        }
        if (!hasStrCmd()) {
          
          return false;
        }
        if (!hasBytesBody()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        Access.AccessReq parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (Access.AccessReq) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required uint64 uint64_uid = 1;
      private long uint64Uid_ ;
      /**
       * <code>required uint64 uint64_uid = 1;</code>
       *
       * <pre>
       *帐号
       * </pre>
       */
      public boolean hasUint64Uid() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required uint64 uint64_uid = 1;</code>
       *
       * <pre>
       *帐号
       * </pre>
       */
      public long getUint64Uid() {
        return uint64Uid_;
      }
      /**
       * <code>required uint64 uint64_uid = 1;</code>
       *
       * <pre>
       *帐号
       * </pre>
       */
      public Builder setUint64Uid(long value) {
        bitField0_ |= 0x00000001;
        uint64Uid_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required uint64 uint64_uid = 1;</code>
       *
       * <pre>
       *帐号
       * </pre>
       */
      public Builder clearUint64Uid() {
        bitField0_ = (bitField0_ & ~0x00000001);
        uint64Uid_ = 0L;
        onChanged();
        return this;
      }

      // required uint32 uint32_seq = 2;
      private int uint32Seq_ ;
      /**
       * <code>required uint32 uint32_seq = 2;</code>
       *
       * <pre>
       *请求包序号
       * </pre>
       */
      public boolean hasUint32Seq() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required uint32 uint32_seq = 2;</code>
       *
       * <pre>
       *请求包序号
       * </pre>
       */
      public int getUint32Seq() {
        return uint32Seq_;
      }
      /**
       * <code>required uint32 uint32_seq = 2;</code>
       *
       * <pre>
       *请求包序号
       * </pre>
       */
      public Builder setUint32Seq(int value) {
        bitField0_ |= 0x00000002;
        uint32Seq_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required uint32 uint32_seq = 2;</code>
       *
       * <pre>
       *请求包序号
       * </pre>
       */
      public Builder clearUint32Seq() {
        bitField0_ = (bitField0_ & ~0x00000002);
        uint32Seq_ = 0;
        onChanged();
        return this;
      }

      // required string str_cmd = 3;
      private java.lang.Object strCmd_ = "";
      /**
       * <code>required string str_cmd = 3;</code>
       *
       * <pre>
       *请求的命令字
       * </pre>
       */
      public boolean hasStrCmd() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required string str_cmd = 3;</code>
       *
       * <pre>
       *请求的命令字
       * </pre>
       */
      public java.lang.String getStrCmd() {
        java.lang.Object ref = strCmd_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          strCmd_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string str_cmd = 3;</code>
       *
       * <pre>
       *请求的命令字
       * </pre>
       */
      public com.google.protobuf.ByteString
          getStrCmdBytes() {
        java.lang.Object ref = strCmd_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          strCmd_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string str_cmd = 3;</code>
       *
       * <pre>
       *请求的命令字
       * </pre>
       */
      public Builder setStrCmd(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        strCmd_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string str_cmd = 3;</code>
       *
       * <pre>
       *请求的命令字
       * </pre>
       */
      public Builder clearStrCmd() {
        bitField0_ = (bitField0_ & ~0x00000004);
        strCmd_ = getDefaultInstance().getStrCmd();
        onChanged();
        return this;
      }
      /**
       * <code>required string str_cmd = 3;</code>
       *
       * <pre>
       *请求的命令字
       * </pre>
       */
      public Builder setStrCmdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        strCmd_ = value;
        onChanged();
        return this;
      }

      // required bytes bytes_body = 4;
      private com.google.protobuf.ByteString bytesBody_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>required bytes bytes_body = 4;</code>
       *
       * <pre>
       *请求信令包体，该字段为protocol序列化内容
       * </pre>
       */
      public boolean hasBytesBody() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>required bytes bytes_body = 4;</code>
       *
       * <pre>
       *请求信令包体，该字段为protocol序列化内容
       * </pre>
       */
      public com.google.protobuf.ByteString getBytesBody() {
        return bytesBody_;
      }
      /**
       * <code>required bytes bytes_body = 4;</code>
       *
       * <pre>
       *请求信令包体，该字段为protocol序列化内容
       * </pre>
       */
      public Builder setBytesBody(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        bytesBody_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required bytes bytes_body = 4;</code>
       *
       * <pre>
       *请求信令包体，该字段为protocol序列化内容
       * </pre>
       */
      public Builder clearBytesBody() {
        bitField0_ = (bitField0_ & ~0x00000008);
        bytesBody_ = getDefaultInstance().getBytesBody();
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:AccessReq)
    }

    static {
      defaultInstance = new AccessReq(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:AccessReq)
  }

  public interface AccessRespOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required uint32 uint32_seq = 1;
    /**
     * <code>required uint32 uint32_seq = 1;</code>
     *
     * <pre>
     *请求包序号
     * </pre>
     */
    boolean hasUint32Seq();
    /**
     * <code>required uint32 uint32_seq = 1;</code>
     *
     * <pre>
     *请求包序号
     * </pre>
     */
    int getUint32Seq();

    // required bytes bytes_body = 2;
    /**
     * <code>required bytes bytes_body = 2;</code>
     *
     * <pre>
     *响应信令包体，该字段为protocol序列化内容
     * </pre>
     */
    boolean hasBytesBody();
    /**
     * <code>required bytes bytes_body = 2;</code>
     *
     * <pre>
     *响应信令包体，该字段为protocol序列化内容
     * </pre>
     */
    com.google.protobuf.ByteString getBytesBody();
  }
  /**
   * Protobuf type {@code AccessResp}
   *
   * <pre>
   *svr回包时会带上客户端请求的 uint32_seq，客户端用来确定是哪次请求的回包，如指定时间未收到后台回报，则客户端需重发
   * </pre>
   */
  public static final class AccessResp extends
      com.google.protobuf.GeneratedMessage
      implements AccessRespOrBuilder {
    // Use AccessResp.newBuilder() to construct.
    private AccessResp(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private AccessResp(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final AccessResp defaultInstance;
    public static AccessResp getDefaultInstance() {
      return defaultInstance;
    }

    public AccessResp getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private AccessResp(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              uint32Seq_ = input.readUInt32();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              bytesBody_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Access.internal_static_AccessResp_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Access.internal_static_AccessResp_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Access.AccessResp.class, Access.AccessResp.Builder.class);
    }

    public static com.google.protobuf.Parser<AccessResp> PARSER =
        new com.google.protobuf.AbstractParser<AccessResp>() {
      public AccessResp parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new AccessResp(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<AccessResp> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required uint32 uint32_seq = 1;
    public static final int UINT32_SEQ_FIELD_NUMBER = 1;
    private int uint32Seq_;
    /**
     * <code>required uint32 uint32_seq = 1;</code>
     *
     * <pre>
     *请求包序号
     * </pre>
     */
    public boolean hasUint32Seq() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required uint32 uint32_seq = 1;</code>
     *
     * <pre>
     *请求包序号
     * </pre>
     */
    public int getUint32Seq() {
      return uint32Seq_;
    }

    // required bytes bytes_body = 2;
    public static final int BYTES_BODY_FIELD_NUMBER = 2;
    private com.google.protobuf.ByteString bytesBody_;
    /**
     * <code>required bytes bytes_body = 2;</code>
     *
     * <pre>
     *响应信令包体，该字段为protocol序列化内容
     * </pre>
     */
    public boolean hasBytesBody() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required bytes bytes_body = 2;</code>
     *
     * <pre>
     *响应信令包体，该字段为protocol序列化内容
     * </pre>
     */
    public com.google.protobuf.ByteString getBytesBody() {
      return bytesBody_;
    }

    private void initFields() {
      uint32Seq_ = 0;
      bytesBody_ = com.google.protobuf.ByteString.EMPTY;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasUint32Seq()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasBytesBody()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeUInt32(1, uint32Seq_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, bytesBody_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(1, uint32Seq_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, bytesBody_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static Access.AccessResp parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Access.AccessResp parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Access.AccessResp parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Access.AccessResp parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Access.AccessResp parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static Access.AccessResp parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static Access.AccessResp parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static Access.AccessResp parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static Access.AccessResp parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static Access.AccessResp parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(Access.AccessResp prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code AccessResp}
     *
     * <pre>
     *svr回包时会带上客户端请求的 uint32_seq，客户端用来确定是哪次请求的回包，如指定时间未收到后台回报，则客户端需重发
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements Access.AccessRespOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return Access.internal_static_AccessResp_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return Access.internal_static_AccessResp_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                Access.AccessResp.class, Access.AccessResp.Builder.class);
      }

      // Construct using Access.AccessResp.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        uint32Seq_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        bytesBody_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return Access.internal_static_AccessResp_descriptor;
      }

      public Access.AccessResp getDefaultInstanceForType() {
        return Access.AccessResp.getDefaultInstance();
      }

      public Access.AccessResp build() {
        Access.AccessResp result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public Access.AccessResp buildPartial() {
        Access.AccessResp result = new Access.AccessResp(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.uint32Seq_ = uint32Seq_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.bytesBody_ = bytesBody_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof Access.AccessResp) {
          return mergeFrom((Access.AccessResp)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(Access.AccessResp other) {
        if (other == Access.AccessResp.getDefaultInstance()) return this;
        if (other.hasUint32Seq()) {
          setUint32Seq(other.getUint32Seq());
        }
        if (other.hasBytesBody()) {
          setBytesBody(other.getBytesBody());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasUint32Seq()) {
          
          return false;
        }
        if (!hasBytesBody()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        Access.AccessResp parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (Access.AccessResp) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required uint32 uint32_seq = 1;
      private int uint32Seq_ ;
      /**
       * <code>required uint32 uint32_seq = 1;</code>
       *
       * <pre>
       *请求包序号
       * </pre>
       */
      public boolean hasUint32Seq() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required uint32 uint32_seq = 1;</code>
       *
       * <pre>
       *请求包序号
       * </pre>
       */
      public int getUint32Seq() {
        return uint32Seq_;
      }
      /**
       * <code>required uint32 uint32_seq = 1;</code>
       *
       * <pre>
       *请求包序号
       * </pre>
       */
      public Builder setUint32Seq(int value) {
        bitField0_ |= 0x00000001;
        uint32Seq_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required uint32 uint32_seq = 1;</code>
       *
       * <pre>
       *请求包序号
       * </pre>
       */
      public Builder clearUint32Seq() {
        bitField0_ = (bitField0_ & ~0x00000001);
        uint32Seq_ = 0;
        onChanged();
        return this;
      }

      // required bytes bytes_body = 2;
      private com.google.protobuf.ByteString bytesBody_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>required bytes bytes_body = 2;</code>
       *
       * <pre>
       *响应信令包体，该字段为protocol序列化内容
       * </pre>
       */
      public boolean hasBytesBody() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required bytes bytes_body = 2;</code>
       *
       * <pre>
       *响应信令包体，该字段为protocol序列化内容
       * </pre>
       */
      public com.google.protobuf.ByteString getBytesBody() {
        return bytesBody_;
      }
      /**
       * <code>required bytes bytes_body = 2;</code>
       *
       * <pre>
       *响应信令包体，该字段为protocol序列化内容
       * </pre>
       */
      public Builder setBytesBody(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        bytesBody_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required bytes bytes_body = 2;</code>
       *
       * <pre>
       *响应信令包体，该字段为protocol序列化内容
       * </pre>
       */
      public Builder clearBytesBody() {
        bitField0_ = (bitField0_ & ~0x00000002);
        bytesBody_ = getDefaultInstance().getBytesBody();
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:AccessResp)
    }

    static {
      defaultInstance = new AccessResp(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:AccessResp)
  }

  public interface PushReqOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required uint64 uint64_uid = 1;
    /**
     * <code>required uint64 uint64_uid = 1;</code>
     *
     * <pre>
     *帐号
     * </pre>
     */
    boolean hasUint64Uid();
    /**
     * <code>required uint64 uint64_uid = 1;</code>
     *
     * <pre>
     *帐号
     * </pre>
     */
    long getUint64Uid();

    // required uint32 uint32_seq = 2;
    /**
     * <code>required uint32 uint32_seq = 2;</code>
     *
     * <pre>
     *Push包序号
     * </pre>
     */
    boolean hasUint32Seq();
    /**
     * <code>required uint32 uint32_seq = 2;</code>
     *
     * <pre>
     *Push包序号
     * </pre>
     */
    int getUint32Seq();

    // required string str_cmd = 3;
    /**
     * <code>required string str_cmd = 3;</code>
     *
     * <pre>
     *Push命令字
     * </pre>
     */
    boolean hasStrCmd();
    /**
     * <code>required string str_cmd = 3;</code>
     *
     * <pre>
     *Push命令字
     * </pre>
     */
    java.lang.String getStrCmd();
    /**
     * <code>required string str_cmd = 3;</code>
     *
     * <pre>
     *Push命令字
     * </pre>
     */
    com.google.protobuf.ByteString
        getStrCmdBytes();

    // required bytes bytes_body = 4;
    /**
     * <code>required bytes bytes_body = 4;</code>
     *
     * <pre>
     *Push信令包体，该字段为protocol序列化内容
     * </pre>
     */
    boolean hasBytesBody();
    /**
     * <code>required bytes bytes_body = 4;</code>
     *
     * <pre>
     *Push信令包体，该字段为protocol序列化内容
     * </pre>
     */
    com.google.protobuf.ByteString getBytesBody();
  }
  /**
   * Protobuf type {@code PushReq}
   *
   * <pre>
   *svr会主动给客户端推送一些指令，客户端依照 str_cmd 来区分 bytes_body 应该使用那个 proto 协议来解
   * </pre>
   */
  public static final class PushReq extends
      com.google.protobuf.GeneratedMessage
      implements PushReqOrBuilder {
    // Use PushReq.newBuilder() to construct.
    private PushReq(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private PushReq(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final PushReq defaultInstance;
    public static PushReq getDefaultInstance() {
      return defaultInstance;
    }

    public PushReq getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private PushReq(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              uint64Uid_ = input.readUInt64();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              uint32Seq_ = input.readUInt32();
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              strCmd_ = input.readBytes();
              break;
            }
            case 34: {
              bitField0_ |= 0x00000008;
              bytesBody_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Access.internal_static_PushReq_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Access.internal_static_PushReq_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Access.PushReq.class, Access.PushReq.Builder.class);
    }

    public static com.google.protobuf.Parser<PushReq> PARSER =
        new com.google.protobuf.AbstractParser<PushReq>() {
      public PushReq parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new PushReq(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<PushReq> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required uint64 uint64_uid = 1;
    public static final int UINT64_UID_FIELD_NUMBER = 1;
    private long uint64Uid_;
    /**
     * <code>required uint64 uint64_uid = 1;</code>
     *
     * <pre>
     *帐号
     * </pre>
     */
    public boolean hasUint64Uid() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required uint64 uint64_uid = 1;</code>
     *
     * <pre>
     *帐号
     * </pre>
     */
    public long getUint64Uid() {
      return uint64Uid_;
    }

    // required uint32 uint32_seq = 2;
    public static final int UINT32_SEQ_FIELD_NUMBER = 2;
    private int uint32Seq_;
    /**
     * <code>required uint32 uint32_seq = 2;</code>
     *
     * <pre>
     *Push包序号
     * </pre>
     */
    public boolean hasUint32Seq() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required uint32 uint32_seq = 2;</code>
     *
     * <pre>
     *Push包序号
     * </pre>
     */
    public int getUint32Seq() {
      return uint32Seq_;
    }

    // required string str_cmd = 3;
    public static final int STR_CMD_FIELD_NUMBER = 3;
    private java.lang.Object strCmd_;
    /**
     * <code>required string str_cmd = 3;</code>
     *
     * <pre>
     *Push命令字
     * </pre>
     */
    public boolean hasStrCmd() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required string str_cmd = 3;</code>
     *
     * <pre>
     *Push命令字
     * </pre>
     */
    public java.lang.String getStrCmd() {
      java.lang.Object ref = strCmd_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          strCmd_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string str_cmd = 3;</code>
     *
     * <pre>
     *Push命令字
     * </pre>
     */
    public com.google.protobuf.ByteString
        getStrCmdBytes() {
      java.lang.Object ref = strCmd_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        strCmd_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // required bytes bytes_body = 4;
    public static final int BYTES_BODY_FIELD_NUMBER = 4;
    private com.google.protobuf.ByteString bytesBody_;
    /**
     * <code>required bytes bytes_body = 4;</code>
     *
     * <pre>
     *Push信令包体，该字段为protocol序列化内容
     * </pre>
     */
    public boolean hasBytesBody() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>required bytes bytes_body = 4;</code>
     *
     * <pre>
     *Push信令包体，该字段为protocol序列化内容
     * </pre>
     */
    public com.google.protobuf.ByteString getBytesBody() {
      return bytesBody_;
    }

    private void initFields() {
      uint64Uid_ = 0L;
      uint32Seq_ = 0;
      strCmd_ = "";
      bytesBody_ = com.google.protobuf.ByteString.EMPTY;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasUint64Uid()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasUint32Seq()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasStrCmd()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasBytesBody()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeUInt64(1, uint64Uid_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeUInt32(2, uint32Seq_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getStrCmdBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBytes(4, bytesBody_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(1, uint64Uid_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(2, uint32Seq_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getStrCmdBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, bytesBody_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static Access.PushReq parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Access.PushReq parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Access.PushReq parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Access.PushReq parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Access.PushReq parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static Access.PushReq parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static Access.PushReq parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static Access.PushReq parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static Access.PushReq parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static Access.PushReq parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(Access.PushReq prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code PushReq}
     *
     * <pre>
     *svr会主动给客户端推送一些指令，客户端依照 str_cmd 来区分 bytes_body 应该使用那个 proto 协议来解
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements Access.PushReqOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return Access.internal_static_PushReq_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return Access.internal_static_PushReq_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                Access.PushReq.class, Access.PushReq.Builder.class);
      }

      // Construct using Access.PushReq.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        uint64Uid_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000001);
        uint32Seq_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        strCmd_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        bytesBody_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return Access.internal_static_PushReq_descriptor;
      }

      public Access.PushReq getDefaultInstanceForType() {
        return Access.PushReq.getDefaultInstance();
      }

      public Access.PushReq build() {
        Access.PushReq result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public Access.PushReq buildPartial() {
        Access.PushReq result = new Access.PushReq(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.uint64Uid_ = uint64Uid_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.uint32Seq_ = uint32Seq_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.strCmd_ = strCmd_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.bytesBody_ = bytesBody_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof Access.PushReq) {
          return mergeFrom((Access.PushReq)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(Access.PushReq other) {
        if (other == Access.PushReq.getDefaultInstance()) return this;
        if (other.hasUint64Uid()) {
          setUint64Uid(other.getUint64Uid());
        }
        if (other.hasUint32Seq()) {
          setUint32Seq(other.getUint32Seq());
        }
        if (other.hasStrCmd()) {
          bitField0_ |= 0x00000004;
          strCmd_ = other.strCmd_;
          onChanged();
        }
        if (other.hasBytesBody()) {
          setBytesBody(other.getBytesBody());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasUint64Uid()) {
          
          return false;
        }
        if (!hasUint32Seq()) {
          
          return false;
        }
        if (!hasStrCmd()) {
          
          return false;
        }
        if (!hasBytesBody()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        Access.PushReq parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (Access.PushReq) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required uint64 uint64_uid = 1;
      private long uint64Uid_ ;
      /**
       * <code>required uint64 uint64_uid = 1;</code>
       *
       * <pre>
       *帐号
       * </pre>
       */
      public boolean hasUint64Uid() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required uint64 uint64_uid = 1;</code>
       *
       * <pre>
       *帐号
       * </pre>
       */
      public long getUint64Uid() {
        return uint64Uid_;
      }
      /**
       * <code>required uint64 uint64_uid = 1;</code>
       *
       * <pre>
       *帐号
       * </pre>
       */
      public Builder setUint64Uid(long value) {
        bitField0_ |= 0x00000001;
        uint64Uid_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required uint64 uint64_uid = 1;</code>
       *
       * <pre>
       *帐号
       * </pre>
       */
      public Builder clearUint64Uid() {
        bitField0_ = (bitField0_ & ~0x00000001);
        uint64Uid_ = 0L;
        onChanged();
        return this;
      }

      // required uint32 uint32_seq = 2;
      private int uint32Seq_ ;
      /**
       * <code>required uint32 uint32_seq = 2;</code>
       *
       * <pre>
       *Push包序号
       * </pre>
       */
      public boolean hasUint32Seq() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required uint32 uint32_seq = 2;</code>
       *
       * <pre>
       *Push包序号
       * </pre>
       */
      public int getUint32Seq() {
        return uint32Seq_;
      }
      /**
       * <code>required uint32 uint32_seq = 2;</code>
       *
       * <pre>
       *Push包序号
       * </pre>
       */
      public Builder setUint32Seq(int value) {
        bitField0_ |= 0x00000002;
        uint32Seq_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required uint32 uint32_seq = 2;</code>
       *
       * <pre>
       *Push包序号
       * </pre>
       */
      public Builder clearUint32Seq() {
        bitField0_ = (bitField0_ & ~0x00000002);
        uint32Seq_ = 0;
        onChanged();
        return this;
      }

      // required string str_cmd = 3;
      private java.lang.Object strCmd_ = "";
      /**
       * <code>required string str_cmd = 3;</code>
       *
       * <pre>
       *Push命令字
       * </pre>
       */
      public boolean hasStrCmd() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required string str_cmd = 3;</code>
       *
       * <pre>
       *Push命令字
       * </pre>
       */
      public java.lang.String getStrCmd() {
        java.lang.Object ref = strCmd_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          strCmd_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string str_cmd = 3;</code>
       *
       * <pre>
       *Push命令字
       * </pre>
       */
      public com.google.protobuf.ByteString
          getStrCmdBytes() {
        java.lang.Object ref = strCmd_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          strCmd_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string str_cmd = 3;</code>
       *
       * <pre>
       *Push命令字
       * </pre>
       */
      public Builder setStrCmd(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        strCmd_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string str_cmd = 3;</code>
       *
       * <pre>
       *Push命令字
       * </pre>
       */
      public Builder clearStrCmd() {
        bitField0_ = (bitField0_ & ~0x00000004);
        strCmd_ = getDefaultInstance().getStrCmd();
        onChanged();
        return this;
      }
      /**
       * <code>required string str_cmd = 3;</code>
       *
       * <pre>
       *Push命令字
       * </pre>
       */
      public Builder setStrCmdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        strCmd_ = value;
        onChanged();
        return this;
      }

      // required bytes bytes_body = 4;
      private com.google.protobuf.ByteString bytesBody_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>required bytes bytes_body = 4;</code>
       *
       * <pre>
       *Push信令包体，该字段为protocol序列化内容
       * </pre>
       */
      public boolean hasBytesBody() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>required bytes bytes_body = 4;</code>
       *
       * <pre>
       *Push信令包体，该字段为protocol序列化内容
       * </pre>
       */
      public com.google.protobuf.ByteString getBytesBody() {
        return bytesBody_;
      }
      /**
       * <code>required bytes bytes_body = 4;</code>
       *
       * <pre>
       *Push信令包体，该字段为protocol序列化内容
       * </pre>
       */
      public Builder setBytesBody(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        bytesBody_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required bytes bytes_body = 4;</code>
       *
       * <pre>
       *Push信令包体，该字段为protocol序列化内容
       * </pre>
       */
      public Builder clearBytesBody() {
        bitField0_ = (bitField0_ & ~0x00000008);
        bytesBody_ = getDefaultInstance().getBytesBody();
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:PushReq)
    }

    static {
      defaultInstance = new PushReq(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:PushReq)
  }

  public interface PushRespOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required uint32 uint32_seq = 1;
    /**
     * <code>required uint32 uint32_seq = 1;</code>
     *
     * <pre>
     *Push包序号
     * </pre>
     */
    boolean hasUint32Seq();
    /**
     * <code>required uint32 uint32_seq = 1;</code>
     *
     * <pre>
     *Push包序号
     * </pre>
     */
    int getUint32Seq();
  }
  /**
   * Protobuf type {@code PushResp}
   *
   * <pre>
   *客户端需要把Push包里的 uint32_seq 回传给接入服务器，用来确认客户端已经收到该 Push，否则svr会进行1次重发
   * </pre>
   */
  public static final class PushResp extends
      com.google.protobuf.GeneratedMessage
      implements PushRespOrBuilder {
    // Use PushResp.newBuilder() to construct.
    private PushResp(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private PushResp(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final PushResp defaultInstance;
    public static PushResp getDefaultInstance() {
      return defaultInstance;
    }

    public PushResp getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private PushResp(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              uint32Seq_ = input.readUInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Access.internal_static_PushResp_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Access.internal_static_PushResp_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Access.PushResp.class, Access.PushResp.Builder.class);
    }

    public static com.google.protobuf.Parser<PushResp> PARSER =
        new com.google.protobuf.AbstractParser<PushResp>() {
      public PushResp parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new PushResp(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<PushResp> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required uint32 uint32_seq = 1;
    public static final int UINT32_SEQ_FIELD_NUMBER = 1;
    private int uint32Seq_;
    /**
     * <code>required uint32 uint32_seq = 1;</code>
     *
     * <pre>
     *Push包序号
     * </pre>
     */
    public boolean hasUint32Seq() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required uint32 uint32_seq = 1;</code>
     *
     * <pre>
     *Push包序号
     * </pre>
     */
    public int getUint32Seq() {
      return uint32Seq_;
    }

    private void initFields() {
      uint32Seq_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasUint32Seq()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeUInt32(1, uint32Seq_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(1, uint32Seq_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static Access.PushResp parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Access.PushResp parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Access.PushResp parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Access.PushResp parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Access.PushResp parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static Access.PushResp parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static Access.PushResp parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static Access.PushResp parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static Access.PushResp parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static Access.PushResp parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(Access.PushResp prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code PushResp}
     *
     * <pre>
     *客户端需要把Push包里的 uint32_seq 回传给接入服务器，用来确认客户端已经收到该 Push，否则svr会进行1次重发
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements Access.PushRespOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return Access.internal_static_PushResp_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return Access.internal_static_PushResp_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                Access.PushResp.class, Access.PushResp.Builder.class);
      }

      // Construct using Access.PushResp.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        uint32Seq_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return Access.internal_static_PushResp_descriptor;
      }

      public Access.PushResp getDefaultInstanceForType() {
        return Access.PushResp.getDefaultInstance();
      }

      public Access.PushResp build() {
        Access.PushResp result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public Access.PushResp buildPartial() {
        Access.PushResp result = new Access.PushResp(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.uint32Seq_ = uint32Seq_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof Access.PushResp) {
          return mergeFrom((Access.PushResp)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(Access.PushResp other) {
        if (other == Access.PushResp.getDefaultInstance()) return this;
        if (other.hasUint32Seq()) {
          setUint32Seq(other.getUint32Seq());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasUint32Seq()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        Access.PushResp parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (Access.PushResp) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required uint32 uint32_seq = 1;
      private int uint32Seq_ ;
      /**
       * <code>required uint32 uint32_seq = 1;</code>
       *
       * <pre>
       *Push包序号
       * </pre>
       */
      public boolean hasUint32Seq() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required uint32 uint32_seq = 1;</code>
       *
       * <pre>
       *Push包序号
       * </pre>
       */
      public int getUint32Seq() {
        return uint32Seq_;
      }
      /**
       * <code>required uint32 uint32_seq = 1;</code>
       *
       * <pre>
       *Push包序号
       * </pre>
       */
      public Builder setUint32Seq(int value) {
        bitField0_ |= 0x00000001;
        uint32Seq_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required uint32 uint32_seq = 1;</code>
       *
       * <pre>
       *Push包序号
       * </pre>
       */
      public Builder clearUint32Seq() {
        bitField0_ = (bitField0_ & ~0x00000001);
        uint32Seq_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:PushResp)
    }

    static {
      defaultInstance = new PushResp(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:PushResp)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_AccessReq_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_AccessReq_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_AccessResp_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_AccessResp_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_PushReq_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_PushReq_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_PushResp_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_PushResp_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\nl\\\\vmware-host/Shared Folders/\316\304\270\345/afte" +
      "rworkdev/smile/src/Smile/src/com/heme/lo" +
      "gic/module/protos/access.proto\"X\n\tAccess" +
      "Req\022\022\n\nuint64_uid\030\001 \002(\004\022\022\n\nuint32_seq\030\002 " +
      "\002(\r\022\017\n\007str_cmd\030\003 \002(\t\022\022\n\nbytes_body\030\004 \002(\014" +
      "\"4\n\nAccessResp\022\022\n\nuint32_seq\030\001 \002(\r\022\022\n\nby" +
      "tes_body\030\002 \002(\014\"V\n\007PushReq\022\022\n\nuint64_uid\030" +
      "\001 \002(\004\022\022\n\nuint32_seq\030\002 \002(\r\022\017\n\007str_cmd\030\003 \002" +
      "(\t\022\022\n\nbytes_body\030\004 \002(\014\"\036\n\010PushResp\022\022\n\nui" +
      "nt32_seq\030\001 \002(\r"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_AccessReq_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_AccessReq_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_AccessReq_descriptor,
              new java.lang.String[] { "Uint64Uid", "Uint32Seq", "StrCmd", "BytesBody", });
          internal_static_AccessResp_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_AccessResp_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_AccessResp_descriptor,
              new java.lang.String[] { "Uint32Seq", "BytesBody", });
          internal_static_PushReq_descriptor =
            getDescriptor().getMessageTypes().get(2);
          internal_static_PushReq_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_PushReq_descriptor,
              new java.lang.String[] { "Uint64Uid", "Uint32Seq", "StrCmd", "BytesBody", });
          internal_static_PushResp_descriptor =
            getDescriptor().getMessageTypes().get(3);
          internal_static_PushResp_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_PushResp_descriptor,
              new java.lang.String[] { "Uint32Seq", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
