package com.heme.logic.module;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;

import com.google.protobuf.InvalidProtocolBufferException;
import com.heme.logic.module.Message.ClassInfo;
import com.heme.logic.module.Message.CommonMsg;
import com.heme.logic.module.Message.ContentType;
import com.heme.logic.module.Message.FileInfo;
import com.heme.logic.module.Message.MessageType;
import com.heme.logic.module.Message.NetGuardInfo;
import com.heme.logic.module.Message.PicMsgInfo;
import com.heme.logic.module.Message.RichInfo;
import com.heme.logic.module.Message.VerifyRequest;
import com.heme.logic.module.Message.VideoMsgInfo;
import com.heme.logic.module.Message.VoiceMsgInfo;
import com.heme.logic.module.Message.CommonMsg.Builder;
import com.heme.logic.module.Message.VoiceTestInfo;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table COMMON_MSG.
*/
public class CommonMsgDao extends AbstractDao<CommonMsg, Long> {

    public static final String TABLENAME = "COMMON_MSG";

    /**
     * Properties of entity CommonMsg.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Uint64MsgId = new Property(0, Long.class, "Uint64MsgId", true, "UINT64_MSG_ID");
        public final static Property Uint64FromUid = new Property(1, long.class, "Uint64FromUid", false, "UINT64_FROM_UID");
        public final static Property Uint64ToUid = new Property(2, Long.class, "Uint64ToUid", false, "UINT64_TO_UID");
        public final static Property Uint64ToGid = new Property(3, Long.class, "Uint64ToGid", false, "UINT64_TO_GID");
        public final static Property Uint32MsgType = new Property(4, int.class, "Uint32MsgType", false, "UINT32_MSG_TYPE");
        public final static Property Uint32ContentType = new Property(5, Integer.class, "Uint32ContentType", false, "UINT32_CONTENT_TYPE");
        public final static Property StrTextMsg = new Property(6, String.class, "StrTextMsg", false, "STR_TEXT_MSG");
        public final static Property MsgPicMsg = new Property(7, byte[].class, "MsgPicMsg", false, "MSG_PIC_MSG");
        public final static Property MsgVoiceMsg = new Property(8, byte[].class, "MsgVoiceMsg", false, "MSG_VOICE_MSG");
        public final static Property MsgVideoMsg = new Property(9, byte[].class, "MsgVideoMsg", false, "MSG_VIDEO_MSG");
        public final static Property MsgMoitorMsg = new Property(10, byte[].class, "MsgMoitorMsg", false, "MSG_MOITOR_MSG");
        public final static Property MsgTestMsg = new Property(11, byte[].class, "MsgTestMsg", false, "MSG_TEST_MSG");
        public final static Property MsgClassInfo = new Property(12, byte[].class, "MsgClassInfo", false, "MSG_CLASS_INFO");
        public final static Property MsgVerifyReq = new Property(13, byte[].class, "MsgVerifyReq", false, "MSG_VERIFY_REQ");
        public final static Property MsgFileInfo = new Property(14, byte[].class, "MsgFileInfo", false, "MSG_FILE_INFO");
        public final static Property MsgRichInfo = new Property(15, byte[].class, "MsgRichInfo", false, "MSG_RICH_INFO");
        public final static Property Uint64Time = new Property(16, Long.class, "Uint64Time", false, "UINT64_TIME");
        public final static Property Uint32TrunctFlag = new Property(17, Integer.class, "Uint32TrunctFlag", false, "UINT32_TRUNCT_FLAG");
    };


    public CommonMsgDao(DaoConfig config) {
        super(config);
    }
    
    public CommonMsgDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "'COMMON_MSG' (" + //
                "'UINT64_MSG_ID' INTEGER PRIMARY KEY ," + // 0: Uint64MsgId
                "'UINT64_FROM_UID' INTEGER NOT NULL ," + // 1: Uint64FromUid
                "'UINT64_TO_UID' INTEGER," + // 2: Uint64ToUid
                "'UINT64_TO_GID' INTEGER," + // 3: Uint64ToGid
                "'UINT32_MSG_TYPE' INTEGER NOT NULL ," + // 4: Uint32MsgType
                "'UINT32_CONTENT_TYPE' INTEGER," + // 5: Uint32ContentType
                "'STR_TEXT_MSG' TEXT," + // 6: StrTextMsg
                "'MSG_PIC_MSG' BLOB," + // 7: MsgPicMsg
                "'MSG_VOICE_MSG' BLOB," + // 8: MsgVoiceMsg
                "'MSG_VIDEO_MSG' BLOB," + // 9: MsgVideoMsg
                "'MSG_MOITOR_MSG' BLOB," + // 10: MsgMoitorMsg
                "'MSG_TEST_MSG' BLOB," + // 11: MsgTestMsg
                "'MSG_CLASS_INFO' BLOB," + // 12: MsgClassInfo
                "'MSG_VERIFY_REQ' BLOB," + // 13: MsgVerifyReq
                "'MSG_FILE_INFO' BLOB," + // 14: MsgFileInfo
                "'MSG_RICH_INFO' BLOB," + // 15: MsgRichInfo
                "'UINT64_TIME' INTEGER," + // 16: Uint64Time
                "'UINT32_TRUNCT_FLAG' INTEGER);"); // 17: Uint32TrunctFlag
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "'COMMON_MSG'";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, CommonMsg entity) {
        stmt.clearBindings();
        if(entity.hasUint64MsgId()) {
            stmt.bindLong(1, entity.getUint64MsgId());
        }
        if(entity.hasUint64FromUid()) {
            stmt.bindLong(2, entity.getUint64FromUid());
        }
        if(entity.getUint64ToUidList() != null && entity.getUint64ToUidCount() > 0) {
            stmt.bindLong(3, entity.getUint64ToUid(0));
        }
        if(entity.getUint64ToGidList() != null && entity.getUint64ToGidCount() > 0) {
            stmt.bindLong(4, entity.getUint64ToGid(0));
        }
        if(entity.hasUint32MsgType()) {
            stmt.bindLong(5, entity.getUint32MsgType().getNumber());
        }
        if(entity.hasUint32ContentType()) {
            stmt.bindLong(6, entity.getUint32ContentType().getNumber());
        }
        if(entity.hasStrTextMsg()) {
            stmt.bindString(7, entity.getStrTextMsg());
        }
        if(entity.hasMsgPicMsg()) {
            stmt.bindBlob(8, entity.getMsgPicMsg().toByteArray());
        }
        if(entity.hasMsgVoiceMsg()) {
            stmt.bindBlob(9, entity.getMsgVoiceMsg().toByteArray());
        }
        if(entity.hasMsgVideoMsg()) {
            stmt.bindBlob(10, entity.getMsgVideoMsg().toByteArray());
        }
        if(entity.hasMsgMoitorMsg()) {
            stmt.bindBlob(11, entity.getMsgMoitorMsg().toByteArray());
        }
        if(entity.hasMsgTestMsg()) {
            stmt.bindBlob(12, entity.getMsgTestMsg().toByteArray());
        }
        if(entity.hasMsgClassInfo()) {
            stmt.bindBlob(13, entity.getMsgClassInfo().toByteArray());
        }
        if(entity.hasMsgVerifyReq()) {
            stmt.bindBlob(14, entity.getMsgVerifyReq().toByteArray());
        }
        if(entity.hasMsgFileInfo()) {
            stmt.bindBlob(15, entity.getMsgFileInfo().toByteArray());
        }
        if(entity.hasMsgRichInfo()) {
            stmt.bindBlob(16, entity.getMsgRichInfo().toByteArray());
        }
        if(entity.hasUint64Time()) {
            stmt.bindLong(17, entity.getUint64Time());
        }
        if(entity.hasUint32TrunctFlag()) {
            stmt.bindLong(18, entity.getUint32TrunctFlag());
        }
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public CommonMsg readEntity(Cursor cursor, int offset) {
        Builder builder = CommonMsg.newBuilder();
        if (!cursor.isNull(offset + 0)) {
            builder.setUint64MsgId(cursor.getLong(offset + 0));
        }
        builder.setUint64FromUid(cursor.getLong(offset + 1));
        if (!cursor.isNull(offset + 2)) {
            builder.setUint64ToUid(0, cursor.getLong(offset + 2));
        }
        if (!cursor.isNull(offset + 3)) {
            builder.setUint64ToGid(0, cursor.getLong(offset + 3));
        }
        builder.setUint32MsgType(MessageType.valueOf(cursor.getInt(offset + 4)));
        if (!cursor.isNull(offset + 5)) {
            builder.setUint32ContentType(ContentType.valueOf(cursor.getInt(offset + 5)));
        }
        if (!cursor.isNull(offset + 6)) {
            builder.setStrTextMsg(cursor.getString(offset + 6));
        }
		try
		{
	        if (!cursor.isNull(offset + 7)) {
				PicMsgInfo picMsgInfo = PicMsgInfo.parseFrom(cursor.getBlob(offset + 7));
	        	builder.setMsgPicMsg(picMsgInfo);
	        }
	        if (!cursor.isNull(offset + 8)) {
	        	VoiceMsgInfo voiceMsgInfo = VoiceMsgInfo.parseFrom(cursor.getBlob(offset + 8));
	            builder.setMsgVoiceMsg(voiceMsgInfo);
	        }
	        if (!cursor.isNull(offset + 9)) {
	            VideoMsgInfo videoMsgInfo = VideoMsgInfo.parseFrom(cursor.getBlob(offset + 9));
	            builder.setMsgVideoMsg(videoMsgInfo);
	        }
	        if (!cursor.isNull(offset + 10)) {
	        	NetGuardInfo netGuardInfo = NetGuardInfo.parseFrom(cursor.getBlob(offset + 10));
	            builder.setMsgMoitorMsg(netGuardInfo);
	            
	        }
	        if (!cursor.isNull(offset + 11)) {
	        	VoiceTestInfo voiceTestInfo = VoiceTestInfo.parseFrom(cursor.getBlob(offset + 11));
	            builder.setMsgTestMsg(voiceTestInfo);
	        }
	        if (!cursor.isNull(offset + 12)) {
	        	ClassInfo classInfo = ClassInfo.parseFrom(cursor.getBlob(offset + 12));
	            builder.setMsgClassInfo(classInfo);
	        }
	        if (!cursor.isNull(offset + 13)) {
	        	VerifyRequest verifyRequest = VerifyRequest.parseFrom(cursor.getBlob(offset + 13));
	            builder.setMsgVerifyReq(verifyRequest);
	        }
	        if (!cursor.isNull(offset + 14)) {
	        	FileInfo fileInfo = FileInfo.parseFrom(cursor.getBlob(offset + 14));
	            builder.setMsgFileInfo(fileInfo);
	        }
	        if (!cursor.isNull(offset + 15)) {
	        	RichInfo richInfo = RichInfo.parseFrom(cursor.getBlob(offset + 15));
	            builder.setMsgRichInfo(richInfo);
	        }

		} catch (InvalidProtocolBufferException e)
		{
			e.printStackTrace();
		}

        if (!cursor.isNull(offset + 16)) {
            builder.setUint64Time(cursor.getLong(offset + 16));
        }
        if (!cursor.isNull(offset + 17)) {
            builder.setUint32TrunctFlag(cursor.getInt(offset + 17));
        }
        return builder.build();
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, CommonMsg entity, int offset) {
        throw new UnsupportedOperationException("Protobuf objects cannot be modified");
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(CommonMsg entity, long rowId) {
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(CommonMsg entity) {
        if(entity != null) {
            return entity.getUint64MsgId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return false;
    }
    
}
