package com.heme.logic.module;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.heme.logic.module.Message.CommonMsg;

import com.heme.logic.module.CommonMsgDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig commonMsgDaoConfig;

    private final CommonMsgDao commonMsgDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        commonMsgDaoConfig = daoConfigMap.get(CommonMsgDao.class).clone();
        commonMsgDaoConfig.initIdentityScope(type);

        commonMsgDao = new CommonMsgDao(commonMsgDaoConfig, this);

        registerDao(CommonMsg.class, commonMsgDao);
    }
    
    public void clear() {
        commonMsgDaoConfig.getIdentityScope().clear();
    }

    public CommonMsgDao getCommonMsgDao() {
        return commonMsgDao;
    }

}
